# Generated by Django 4.2.11 on 2024-03-21 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0003_alter_newspaper_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newspaper",
            name="publisher",
        ),
        migrations.AddField(
            model_name="newspaper",
            name="publisher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newspapers",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
